### ISSUE TITLE
2Pack install failed

### ISSUE THREAD

**Issue by jiangchen3512** [pshepetko/org.idempiere.mfg#3]
error log:
DB.executeUpdate: UPDATE PP_Order_Workflow SET Created='getDate()' WHERE Created IS NULL [PipoDS_14e202be-ae97-4875-a2c0-ef8e66dfcd62] [101]
org.postgresql.util.PSQLException: ERROR: invalid input syntax for type timestamp: "getDate()"
  位置：38; State=22007; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
	at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.compiere.db.StatementProxy.invoke(StatementProxy.java:130)
	at com.sun.proxy.$Proxy12.executeUpdate(Unknown Source)
	at org.compiere.util.DB.executeUpdate(DB.java:1044)
	at org.compiere.util.DB.executeUpdate(DB.java:943)
	at org.compiere.util.DB.executeUpdate(DB.java:929)
	at org.adempiere.pipo2.handler.ColumnElementHandler.createColumn(ColumnElementHandler.java:300)
	at org.adempiere.pipo2.handler.ColumnElementHandler.syncColumn(ColumnElementHandler.java:195)
	at org.adempiere.pipo2.handler.ColumnElementHandler.startElement(ColumnElementHandler.java:177)
	at org.adempiere.pipo2.PackInHandler.processElement(PackInHandler.java:237)
	at org.adempiere.pipo2.PackInHandler.processElement(PackInHandler.java:253)

**Comment by pshepetko** [comment]
Hello!
Can you give me your environment : iDempiere, Java, Postgresql  and plugin versions
